# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: 'Install npm dependencies'

- task: YarnInstaller@3
  displayName: 'Install yarn'
  inputs:
    versionSpec: '1.x'
    checkLatest: true

- task: Yarn@3
  displayName: 'Install yarn dependencies'
  inputs:
    arguments: 'install'

- task: Yarn@3
  displayName: 'Create dist package with yarn'
  inputs:
    arguments: 'dist:mac'

